---
name: update aws user-agent variable

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
      - 'stable/**'
    paths:
      - 'galaxy.yml'

jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - name: Dump context
        uses: crazy-max/ghaction-dump-context@v2
  # update-variable:
  #   uses: abikouo/github_actions/.github/workflows/update_aws_user_agent.yml@automate_aws_user_agent_variable