name: Code review
on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  pull-request-size:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"
      - uses: ansible-collections/amazon.aws/.github/actions/pull_request_size@main
        with:
          path: "."
          github_token: ${{ github.token }}